### ISSUE TITLE
crash - wonderful-enchantments-1.16.4-0.10.1.jar

### ISSUE THREAD

**Issue by Atlntssplayer** [Majrusz/WonderfulEnchantmentsMod#7]
Hi, I just had a crash which according to the log might be caused by your mod.
I use the very recent wonderful-enchantments-1.16.4-0.10.1.jar version.

Here is the log. Thx for creating the mod!

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 1/8/21 6:34 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.wonderfulenchantments.enchantments.HunterEnchantment.isValid(HunterEnchantment.java:68) ~[wonderful_enchantments:1.0] {re:classloading}
	at com.wonderfulenchantments.enchantments.HunterEnchantment.spawnExtraLoot(HunterEnchantment.java:36) ~[wonderful_enchantments:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_399_HunterEnchantment_spawnExtraLoot_LootingLevelEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.getLootingLevel(ForgeHooks.java:382) ~[forge:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.getLootingLevel(ForgeHooks.java:375) ~[forge:?] {re:classloading}
	at net.minecraft.loot.LootContext.getLootingModifier(LootContext.java:98) ~[?:?] {re:classloading}
	at net.minecraft.loot.conditions.RandomChanceWithLooting.test(RandomChanceWithLooting.java:36) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.loot.conditions.RandomChanceWithLooting.test(RandomChanceWithLooting.java:18) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.util.function.Predicate.lambda$and$0(Unknown Source) ~[?:1.8.0_271] {}
	at net.minecraft.loot.LootPool.func_216091_a(LootPool.java:84) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.loot.LootTable.func_216114_a(LootTable.java:68) ~[?:?] {re:classloading}
	at net.minecraft.loot.TableLootEntry.func_216154_a(SourceFile:33) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.silentchaos512.scalinghealth.loot.TableGlobalModifier.doApply(TableGlobalModifier.java:30) ~[scalinghealth:4.0.2+2] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:53) ~[forge:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1253) ~[forge:?] {re:classloading}
	at net.minecraft.loot.LootTable.func_216113_a(LootTable.java:86) ~[?:?] {re:classloading}
	at net.minecraft.block.AbstractBlock.func_220076_a(AbstractBlock.java:214) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215693_a(AbstractBlock.java:634) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.block.Block.func_220077_a(Block.java:233) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dankstorage.mixins.json:MixinBlock,pl:mixin:A}
	at net.minecraft.block.Block.func_220054_a(Block.java:258) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dankstorage.mixins.json:MixinBlock,pl:mixin:A}
	at net.minecraft.world.World.func_241212_a_(World.java:275) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:common.MixinWorld,pl:mixin:A}
	at net.minecraft.world.IWorldWriter.func_225521_a_(SourceFile:27) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.ai.brain.task.FarmTask.func_212833_d_(FarmTask.java:98) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.task.FarmTask.func_212833_d_(FarmTask.java:28) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.task.Task.func_220377_c(SourceFile:63) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.task.MultiTask.func_220409_b(SourceFile:61) ~[?:?] {re:classloading}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_271] {}
	at net.minecraft.entity.ai.brain.task.MultiTask.func_212833_d_(SourceFile:61) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.task.Task.func_220377_c(SourceFile:63) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.Brain.func_218222_e(SourceFile:521) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.Brain.func_218210_a(SourceFile:466) ~[?:?] {re:classloading}
	at net.minecraft.entity.merchant.villager.VillagerEntity.func_70619_bc(VillagerEntity.java:195) ~[?:?] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:688) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:common.MixinLivingEntity,pl:mixin:APP:imm_ptl_mixins.json:common.collision.MixinLivingEntity_C,pl:mixin:APP:imm_ptl_mixins.json:client.MixinLivingEntity_C,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:common.MixinLivingEntity,pl:mixin:APP:imm_ptl_mixins.json:common.collision.MixinLivingEntity_C,pl:mixin:APP:imm_ptl_mixins.json:client.MixinLivingEntity_C,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.merchant.villager.VillagerEntity.func_70071_h_(VillagerEntity.java:234) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinServerWorld,pl:mixin:A}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:common.MixinWorld,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinServerWorld,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.wonderfulenchantments.enchantments.HunterEnchantment.isValid(HunterEnchantment.java:68) ~[wonderful_enchantments:1.0] {re:classloading}
	at com.wonderfulenchantments.enchantments.HunterEnchantment.spawnExtraLoot(HunterEnchantment.java:36) ~[wonderful_enchantments:1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_399_HunterEnchantment_spawnExtraLoot_LootingLevelEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.getLootingLevel(ForgeHooks.java:382) ~[forge:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.getLootingLevel(ForgeHooks.java:375) ~[forge:?] {re:classloading}
	at net.minecraft.loot.LootContext.getLootingModifier(LootContext.java:98) ~[?:?] {re:classloading}
	at net.minecraft.loot.conditions.RandomChanceWithLooting.test(RandomChanceWithLooting.java:36) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.loot.conditions.RandomChanceWithLooting.test(RandomChanceWithLooting.java:18) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.util.function.Predicate.lambda$and$0(Unknown Source) ~[?:1.8.0_271] {}
	at net.minecraft.loot.LootPool.func_216091_a(LootPool.java:84) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.loot.LootTable.func_216114_a(LootTable.java:68) ~[?:?] {re:classloading}
	at net.minecraft.loot.TableLootEntry.func_216154_a(SourceFile:33) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.silentchaos512.scalinghealth.loot.TableGlobalModifier.doApply(TableGlobalModifier.java:30) ~[scalinghealth:4.0.2+2] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:53) ~[forge:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1253) ~[forge:?] {re:classloading}
	at net.minecraft.loot.LootTable.func_216113_a(LootTable.java:86) ~[?:?] {re:classloading}
	at net.minecraft.block.AbstractBlock.func_220076_a(AbstractBlock.java:214) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215693_a(AbstractBlock.java:634) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.block.Block.func_220077_a(Block.java:233) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dankstorage.mixins.json:MixinBlock,pl:mixin:A}
	at net.minecraft.block.Block.func_220054_a(Block.java:258) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dankstorage.mixins.json:MixinBlock,pl:mixin:A}
	at net.minecraft.world.World.func_241212_a_(World.java:275) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:common.MixinWorld,pl:mixin:A}
	at net.minecraft.world.IWorldWriter.func_225521_a_(SourceFile:27) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.ai.brain.task.FarmTask.func_212833_d_(FarmTask.java:98) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.task.FarmTask.func_212833_d_(FarmTask.java:28) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.task.Task.func_220377_c(SourceFile:63) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.task.MultiTask.func_220409_b(SourceFile:61) ~[?:?] {re:classloading}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_271] {}
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_271] {}
	at net.minecraft.entity.ai.brain.task.MultiTask.func_212833_d_(SourceFile:61) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.task.Task.func_220377_c(SourceFile:63) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.Brain.func_218222_e(SourceFile:521) ~[?:?] {re:classloading}
	at net.minecraft.entity.ai.brain.Brain.func_218210_a(SourceFile:466) ~[?:?] {re:classloading}
	at net.minecraft.entity.merchant.villager.VillagerEntity.func_70619_bc(VillagerEntity.java:195) ~[?:?] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:688) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:common.MixinLivingEntity,pl:mixin:APP:imm_ptl_mixins.json:common.collision.MixinLivingEntity_C,pl:mixin:APP:imm_ptl_mixins.json:client.MixinLivingEntity_C,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:common.MixinLivingEntity,pl:mixin:APP:imm_ptl_mixins.json:common.collision.MixinLivingEntity_C,pl:mixin:APP:imm_ptl_mixins.json:client.MixinLivingEntity_C,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.merchant.villager.VillagerEntity.func_70071_h_(VillagerEntity.java:234) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinServerWorld,pl:mixin:A}
-- Entity being ticked --
Details:
	Entity Type: minecraft:villager (net.minecraft.entity.merchant.villager.VillagerEntity)
	Entity ID: 32593
	Entity Name: Dane
	Entity's Exact location: 93.68, 70.00, 262.30
	Entity's Block location: World: (93,70,262), Chunk: (at 13,4,6 in 5,16; contains blocks 80,0,256 to 95,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -0.02, -0.08, -0.03
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:imm_ptl_mixins.json:common.MixinWorld,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:imm_ptl_mixins.json:common.MixinServerWorld,pl:mixin:A}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Player'/440, l='ServerWorld minecraft:overworld New World fail stuck many items', x=68.05, y=77.50, z=165.39]]
	Chunk stats: ServerChunkCache: 2659
	Level dimension: minecraft:overworld
	Level spawn location: World: (48,61,-15), Chunk: (at 0,3,1 in 3,-1; contains blocks 48,0,-16 to 63,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 4665 game time, 4665 day time
	Level name: New World fail stuck many items
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 110404 (now: false), thunder time: 113423 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}

**Comment by Majrusz** [comment]
Thanks for your feedback! This issue has been fixed in the latest version.
